import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/auth/auth-provider";
import { DetailProfileDTO } from "@/lib/type/profile";
import { profileServerApi } from "@/features/profiles/api/profile.server";
import { QueryProvider } from "@/lib/providers/query-provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/lib/providers/theme-provider";

import { Google_Sans_Flex, Source_Code_Pro } from "next/font/google";

const fontSans = Google_Sans_Flex({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let profile: DetailProfileDTO | null = null

  try {
    profile = await profileServerApi.getMyProfile()

  } catch (_) {
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider user={profile}>
            <QueryProvider>
              <Toaster richColors position={"top-center"} />
              {children}
            </QueryProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}